### PR TITLE
Created Search box and added autocomplete files to js folder

### PR DESCRIPTION
**Pull request by scottaames**

### CODE REVIEW

**Comment by kaitlyndlee** [comment]
Small thing, could you remove the docs from this PR?

**Comment by kaitlyndlee** [comment]
Also since you're moving the autocomplete files into the src code, could you remove the AutoComplete dir?

**Comment by scottaames** [comment]
> Small thing, could you remove the docs from this PR?

Sure - Just wanted to make sure they were there for Chris but i'lll re-add to my gitignore.

**Comment by scottaames** [comment]
aaaaand i acccidentally closed it.

**Comment by scottaames** [comment]
> Also since you're moving the autocomplete files into the src code, could you remove the AutoComplete dir?

Yeah I plan to after the js files are all fixed but I wanted to keep the originals as a back up

**Review by cgm78 — APPROVED** [review]

**Pull request merged**
